version: 0.0.1.{build}
image: Visual Studio 2019

environment:
  matrix:
  - BUILD_OPTION: "Visual Studio 16 2019"
  - BUILD_OPTION: "Visual Studio 16 2019 Win64"

install:
  - choco install doxygen.install

build_script:
- cmd: scripts\appveyor\build.cmd

test_script:
- cmd: scripts\appveyor\test.cmd
