language: cpp
dist: xenial

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7
    - lcov
    - libwxgtk3.0-dev
    - libgtk2.0-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install wxmac   ; fi

matrix:
  include:
  - env: TEST="Build on macOS"
    os: osx
    osx_image: xcode10.3
    script: scripts/travis/build_macos.sh
  - env: TEST="Build on Linux"
    os: linux
    script: scripts/travis/build_linux.sh
  - env: TEST="Coverage"
    os: linux
    script: scripts/travis/coverage.sh
