language: cpp
dist: bionic

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-9
    - lcov
    - libgtk-3-dev
    - doxygen
  homebrew:
    packages:
    - doxygen

matrix:
  include:
  - env: TEST="Build xtd on macOS"
    os: osx
    osx_image: xcode12.2
    script: scripts/travis/build_xtd_on_macos.sh
  - env: TEST="Build xtd and launch unit tests on Linux"
    os: linux
    script: scripts/travis/build_xtd_and_launch_unit_tests_on_linux.sh
