language: cpp
dist: xenial

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7

matrix:
  include:
  - env: TEST="Build on macOS"
    os: osx
    osx_image: xcode10.0
    script: scripts/travis/build_macos.sh
  - env: TEST="Build on Linux"
    os: linux
    script: scripts/travis/build_linux.sh
  - env: TEST="Build with coverage on Linux"
    os: linux
    script: scripts/travis/build_with_coverage_linux.sh
    after_success: scripts/travis/publish_to_codecov.sh
